name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tag:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        tools: composer
        extensions: 'xdebug'
    - uses: actions/checkout@v2
    
    - name: Install Composer dependencies & cache dependencies
      uses: "ramsey/composer-install@v2"
      with:
        composer-options: "--prefer-dist --no-dev --optimize-autoloader"
        custom-cache-key: "composer-7.1-vendor"

    - name: Snapshot vendor
      run: cp -ar ./vendor src/

    - name: Install Composer dependencies & cache dependencies
      uses: "ramsey/composer-install@v2"
      with:
        composer-options: "--prefer-dist"
        custom-cache-key: "composer-7.1"

    - name: Validate composer.json and composer.lock
      run: composer validate
    
    - name: Run Code Sniffer
      run: ./vendor/bin/phpcs --extensions=php --colors -n -s .

    - name: Run Test Suite
      run: XDEBUG_MODE=coverage ./vendor/bin/phpunit tests --coverage-text
