name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tag:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v3
      with:
        dev: yes
        php_version: 7.4
        version: 2.x
    - name: Lint
      uses: php-actions/composer@v3
      with:
        command: exec
        args: "'phpcs --extensions=php --colors -n -s .' --verbose"
        dev: yes
        progress: yes
        interaction: yes
        php_version: 7.4
        version: 2.x
    - name: Snapshot vendor
      run: cp -ar ./vendor src/
    - name: Run Tests
      uses: php-actions/phpunit@v9
      with:
        configuration: phpunit.xml
        php_version: 7.4
        args: --coverage-text
