name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tag:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v2
      with:
        dev: yes
    - name: Lint
      uses: php-actions/composer@v2
      with:
        command: exec
        args: "'phpcs --extensions=php --colors -n -s .' --verbose"
        suggest: yes
        dev: yes
        progress: yes
        interaction: yes
    - name: Snapshot vendor
      run: cp -ar ./vendor src/
    - name: Run Tests
      uses: php-actions/phpunit@v9
      with:
        configuration: phpunit.xml
        args: --coverage-text
