name: Release

on:
  push:
    tags:
    - "*"
  pull_request:
    branches:
    - main


jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v2
      with:
        dev: no
    - name: Build package
      run: cp -ar vendor src/
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        GITHUB_WORKSPACE: ./src
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: enable-svg-uploads
        VERSION: 2.0.21
